<<<<<<< HEAD
=======
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
>>>>>>> b425169 (feat: prisma setup)
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
<<<<<<< HEAD
    url: process.env.DATABASE_URL,
=======
    url: process.env["DATABASE_URL"],
>>>>>>> b425169 (feat: prisma setup)
  },
});
